// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDGl0818BoqS9vekS_DTCY5J1pYJo4RU4',
    appId: '1:206775040380:web:9f379e92f6b539c706ccf9',
    messagingSenderId: '206775040380',
    projectId: 'nestview-bb13b',
    authDomain: 'nestview-bb13b.firebaseapp.com',
    databaseURL: 'https://nestview-bb13b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nestview-bb13b.appspot.com',
    measurementId: 'G-SBHTCQFFJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWUPDr8iPlLquNJgF8fJD1NRmTZS6OFgI',
    appId: '1:206775040380:android:c30acfb313d0ba3e06ccf9',
    messagingSenderId: '206775040380',
    projectId: 'nestview-bb13b',
    databaseURL: 'https://nestview-bb13b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nestview-bb13b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyZRtyQ8TS60PFkh5-734A-2T-ZuFU2bE',
    appId: '1:206775040380:ios:94d1970108a0ddea06ccf9',
    messagingSenderId: '206775040380',
    projectId: 'nestview-bb13b',
    databaseURL: 'https://nestview-bb13b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nestview-bb13b.appspot.com',
    iosClientId: '206775040380-fq1i9thtih0nggune8fpsd1oeh1rs84n.apps.googleusercontent.com',
    iosBundleId: 'com.eco.nestview.nestview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyZRtyQ8TS60PFkh5-734A-2T-ZuFU2bE',
    appId: '1:206775040380:ios:94d1970108a0ddea06ccf9',
    messagingSenderId: '206775040380',
    projectId: 'nestview-bb13b',
    databaseURL: 'https://nestview-bb13b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nestview-bb13b.appspot.com',
    iosClientId: '206775040380-fq1i9thtih0nggune8fpsd1oeh1rs84n.apps.googleusercontent.com',
    iosBundleId: 'com.eco.nestview.nestview',
  );
}
